---
abstract: 'A base class providing config, locking, logging, and l10n'
author:
  - 'Peter Flanigan, C<< <pjfl@cpan.org> >>'
build_requires:
  Class::Null: 1.09
  Exception::Class: 1.23
  Math::BigInt: 1.89
  Test::More: 0.74
configure_requires:
  Module::Build: 0.38
  version: 0.77
dynamic_config: 1
generated_by: 'Module::Build version 0.4004, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Usul
no_index:
  directory:
    - examples
    - inc
    - share
    - t
provides:
  Class::Usul:
    file: lib/Class/Usul.pm
    version: v0.14.277
  Class::Usul::Build:
    file: lib/Class/Usul/Build.pm
    version: v0.14.277
  Class::Usul::Build::InstallActions:
    file: lib/Class/Usul/Build/InstallActions.pm
    version: v0.14.277
  Class::Usul::Build::Questions:
    file: lib/Class/Usul/Build/Questions.pm
    version: v0.14.277
  Class::Usul::Build::VCS:
    file: lib/Class/Usul/Build/VCS.pm
    version: v0.14.277
  Class::Usul::Config:
    file: lib/Class/Usul/Config.pm
    version: v0.14.277
  Class::Usul::Config::Programs:
    file: lib/Class/Usul/Config/Programs.pm
    version: v0.14.277
  Class::Usul::Constants:
    file: lib/Class/Usul/Constants.pm
    version: v0.14.277
  Class::Usul::Constraints:
    file: lib/Class/Usul/Constraints.pm
    version: v0.14.277
  Class::Usul::Crypt:
    file: lib/Class/Usul/Crypt.pm
    version: v0.14.277
  Class::Usul::File:
    file: lib/Class/Usul/File.pm
    version: v0.14.277
  Class::Usul::Functions:
    file: lib/Class/Usul/Functions.pm
    version: v0.14.277
  Class::Usul::IPC:
    file: lib/Class/Usul/IPC.pm
    version: v0.14.277
  Class::Usul::L10N:
    file: lib/Class/Usul/L10N.pm
    version: v0.14.277
  Class::Usul::Log:
    file: lib/Class/Usul/Log.pm
    version: v0.14.277
  Class::Usul::Moose:
    file: lib/Class/Usul/Moose.pm
    version: v0.14.277
  Class::Usul::Plugin::Build::Debian:
    file: lib/Class/Usul/Plugin/Build/Debian.pm
    version: v0.14.277
  Class::Usul::Programs:
    file: lib/Class/Usul/Programs.pm
    version: v0.14.277
  Class::Usul::Response::IPC:
    file: lib/Class/Usul/Response/IPC.pm
    version: v0.14.277
  Class::Usul::Response::Meta:
    file: lib/Class/Usul/Response/Meta.pm
    version: v0.14.277
  Class::Usul::Response::Table:
    file: lib/Class/Usul/Response/Table.pm
    version: v0.14.277
  Class::Usul::Time:
    file: lib/Class/Usul/Time.pm
    version: v0.14.277
  Class::Usul::TraitFor::LoadingClasses:
    file: lib/Class/Usul/TraitFor/LoadingClasses.pm
    version: v0.14.277
  Class::Usul::TraitFor::UntaintedGetopts:
    file: lib/Class/Usul/TraitFor/UntaintedGetopts.pm
    version: v0.14.277
recommends:
  App::cpanminus: 1.6005
  Pod::Markdown: 1.322
  Proc::ProcessTable: 0.42
requires:
  Class::Inspector: 1.24
  Class::Load: 0.18
  Class::Null: 1.09
  Crypt::CBC: 2.3
  Crypt::Twofish2: 1.02
  Data::Printer: 0.24
  Date::Format: 2.22
  DateTime::Format::Epoch: 0.11
  Digest::MD5: 2.39
  Digest::SHA1: 2.11
  Email::Date::Format: 1.002
  File::DataClass: v0.16.0
  File::Gettext: v0.16.0
  Getopt::Mixed: 1.1
  Git::Class: 0.12
  IO::Interactive: v0.0.5
  IPC::Cmd: 0.42
  IPC::Open3: 1.02
  IPC::SRLock: v0.9.0
  Import::Into: 1.001
  Log::Handler: 0.63
  Module::Build: 0.38
  Module::CoreList: 2.24
  Module::Load::Conditional: 0.26
  Module::Pluggable: 3.9
  Moose: 2.0801
  MooseX::Aliases: 0.1
  MooseX::AttributeShortcuts: 0.014
  MooseX::ClassAttribute: 0.27
  MooseX::Getopt: 0.5
  MooseX::MethodAttributes: 0.24
  MooseX::Role::Parameterized: 0.19
  MooseX::Role::WithOverloading: 0.08
  MooseX::Traits::Pluggable: 0.1
  MooseX::Types: 0.25
  MooseX::Types::LoadableClass: 0.007
  POSIX: 1.09
  Path::Class: 0.16
  Perl::Version: 1.009
  Pod::Eventual: 0.09333
  Pod::Man: 2.22
  Pod::Parser: 1.37
  SVN::Class: 0.12
  Scalar::Util: 1.19
  Sub::Exporter: 0.982
  Sub::Exporter::Progressive: 0.001006
  Term::ReadKey: 2.3
  Text::Autoformat: 1.13
  Text::Format: 0.53
  Time::Zone: 2.22
  Try::Tiny: 0.09
  YAML::Syck: 1.05
  namespace::autoclean: 0.09
  namespace::clean: 0.11
  parent: 0.221
  perl: 5.01
  version: 0.77
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Class-Usul
  homepage: http://www.roxsoft.co.uk
  license: http://dev.perl.org/licenses/
version: v0.14.277
