---
abstract: 'A base class providing config, locking, logging, and l10n'
author:
  - 'Peter Flanigan, C<< <pjfl@cpan.org> >>'
build_requires:
  Module::Build: 0.4004
  Test::Deep: 0.108
  version: 0.88
configure_requires:
  Module::Build: 0.4004
  version: 0.88
dynamic_config: 1
generated_by: 'Module::Build version 0.4004, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Usul
no_index:
  directory:
    - examples
    - inc
    - share
    - t
provides:
  Class::Usul:
    file: lib/Class/Usul.pm
    version: v0.22.15
  Class::Usul::Config:
    file: lib/Class/Usul/Config.pm
    version: v0.22.12
  Class::Usul::Config::Programs:
    file: lib/Class/Usul/Config/Programs.pm
    version: v0.22.4
  Class::Usul::Constants:
    file: lib/Class/Usul/Constants.pm
    version: v0.22.3
  Class::Usul::Crypt:
    file: lib/Class/Usul/Crypt.pm
    version: v0.22.10
  Class::Usul::Crypt::Util:
    file: lib/Class/Usul/Crypt/Util.pm
    version: v0.22.12
  Class::Usul::Exception:
    file: lib/Class/Usul/Exception.pm
    version: v0.22.1
  Class::Usul::File:
    file: lib/Class/Usul/File.pm
    version: v0.22.12
  Class::Usul::Functions:
    file: lib/Class/Usul/Functions.pm
    version: v0.22.13
  Class::Usul::IPC:
    file: lib/Class/Usul/IPC.pm
    version: v0.22.4
  Class::Usul::L10N:
    file: lib/Class/Usul/L10N.pm
    version: v0.22.3
  Class::Usul::Lock:
    file: lib/Class/Usul/Lock.pm
    version: v0.22.8
  Class::Usul::Log:
    file: lib/Class/Usul/Log.pm
    version: v0.22.10
  Class::Usul::Programs:
    file: lib/Class/Usul/Programs.pm
    version: v0.22.12
  Class::Usul::Response::IPC:
    file: lib/Class/Usul/Response/IPC.pm
    version: v0.22.2
  Class::Usul::Response::Meta:
    file: lib/Class/Usul/Response/Meta.pm
    version: v0.22.2
  Class::Usul::Response::Table:
    file: lib/Class/Usul/Response/Table.pm
    version: v0.22.2
  Class::Usul::Time:
    file: lib/Class/Usul/Time.pm
    version: v0.22.1
  Class::Usul::TraitFor::LoadingClasses:
    file: lib/Class/Usul/TraitFor/LoadingClasses.pm
    version: v0.22.1
  Class::Usul::TraitFor::UntaintedGetopts:
    file: lib/Class/Usul/TraitFor/UntaintedGetopts.pm
    version: v0.22.13
  Class::Usul::Types:
    file: lib/Class/Usul/Types.pm
    version: v0.22.1
recommends:
  App::cpanminus: 1.6005
  Proc::ProcessTable: 0.42
requires:
  Class::Inspector: 1.24
  Class::Load: 0.18
  Class::Null: 2.10142
  Crypt::CBC: 2.3
  Crypt::Twofish2: 1.02
  Data::Printer: 0.35
  Data::Record: 0.02
  Date::Format: 2.24
  DateTime::Format::Epoch: 0.13
  Digest::SHA1: 2.11
  File::DataClass: v0.22.0
  File::Gettext: v0.18.0
  File::HomeDir: 0.93
  Getopt::Long::Descriptive: 0.093
  IO::Interactive: v0.0.6
  IPC::SRLock: v0.12.0
  JSON: 2.5
  Log::Handler: 0.63
  Moo: 1.002
  MooX::ClassStash: 0.005
  MooX::Options: 3.83
  Path::Class: 0.23
  Pod::Eventual: 0.09333
  Regexp::Common: 2010010201
  Term::ReadKey: 2.3
  Text::Autoformat: 1.669002
  Time::Zone: 2.24
  Try::Tiny: 0.09
  Type::Tiny: 0.012
  Unexpected: v0.4.0
  YAML::Syck: 1.17
  namespace::clean: 0.23
  namespace::sweep: 0.006
  perl: 5.010001
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Class-Usul
  homepage: http://www.roxsoft.co.uk
  license: http://dev.perl.org/licenses/
version: v0.22.15
