---
abstract: 'A base class providing config, locking, logging, and l10n'
author:
  - 'Peter Flanigan, C<< <pjfl@cpan.org> >>'
build_requires:
  Module::Build: 0.4004
  Test::Deep: 0.108
  version: 0.88
configure_requires:
  Module::Build: 0.4004
  version: 0.88
dynamic_config: 1
generated_by: 'Module::Build version 0.4004, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Usul
no_index:
  directory:
    - examples
    - inc
    - share
    - t
provides:
  Class::Usul:
    file: lib/Class/Usul.pm
    version: v0.21.1
  Class::Usul::Config:
    file: lib/Class/Usul/Config.pm
    version: v0.21.1
  Class::Usul::Config::Programs:
    file: lib/Class/Usul/Config/Programs.pm
    version: v0.21.1
  Class::Usul::Constants:
    file: lib/Class/Usul/Constants.pm
    version: v0.21.1
  Class::Usul::Constraints:
    file: lib/Class/Usul/Constraints.pm
    version: v0.21.1
  Class::Usul::Crypt:
    file: lib/Class/Usul/Crypt.pm
    version: v0.21.1
  Class::Usul::Crypt::Util:
    file: lib/Class/Usul/Crypt/Util.pm
    version: v0.21.1
  Class::Usul::Exception:
    file: lib/Class/Usul/Exception.pm
    version: v0.21.1
  Class::Usul::File:
    file: lib/Class/Usul/File.pm
    version: v0.21.1
  Class::Usul::Functions:
    file: lib/Class/Usul/Functions.pm
    version: v0.21.1
  Class::Usul::IPC:
    file: lib/Class/Usul/IPC.pm
    version: v0.21.1
  Class::Usul::L10N:
    file: lib/Class/Usul/L10N.pm
    version: v0.21.1
  Class::Usul::Lock:
    file: lib/Class/Usul/Lock.pm
    version: v0.21.1
  Class::Usul::Log:
    file: lib/Class/Usul/Log.pm
    version: v0.21.1
  Class::Usul::Moose:
    file: lib/Class/Usul/Moose.pm
    version: v0.21.1
  Class::Usul::Programs:
    file: lib/Class/Usul/Programs.pm
    version: v0.21.1
  Class::Usul::Response::IPC:
    file: lib/Class/Usul/Response/IPC.pm
    version: v0.21.1
  Class::Usul::Response::Meta:
    file: lib/Class/Usul/Response/Meta.pm
    version: v0.21.1
  Class::Usul::Response::Table:
    file: lib/Class/Usul/Response/Table.pm
    version: v0.21.1
  Class::Usul::Time:
    file: lib/Class/Usul/Time.pm
    version: v0.21.1
  Class::Usul::TraitFor::LoadingClasses:
    file: lib/Class/Usul/TraitFor/LoadingClasses.pm
    version: v0.21.1
  Class::Usul::TraitFor::UntaintedGetopts:
    file: lib/Class/Usul/TraitFor/UntaintedGetopts.pm
    version: v0.21.1
recommends:
  App::cpanminus: 1.6005
  Proc::ProcessTable: 0.42
requires:
  Class::Inspector: 1.24
  Class::Load: 0.18
  Class::Null: 2.10142
  Crypt::CBC: 2.3
  Crypt::Twofish2: 1.02
  Data::Printer: 0.24
  Date::Format: 2.24
  DateTime::Format::Epoch: 0.13
  Digest::SHA1: 2.11
  File::DataClass: v0.20.0
  File::Gettext: v0.16.0
  File::HomeDir: 0.93
  IO::Interactive: v0.0.6
  IPC::SRLock: v0.11.11
  Import::Into: 1.001
  Log::Handler: 0.63
  Moose: 2.0802
  MooseX::Aliases: 0.1
  MooseX::AttributeShortcuts: 0.014
  MooseX::ClassAttribute: 0.27
  MooseX::Getopt: 0.56
  MooseX::MethodAttributes: 0.24
  MooseX::Types: 0.35
  MooseX::Types::Common: 0.001008
  MooseX::Types::LoadableClass: 0.008
  Path::Class: 0.23
  Sub::Exporter: 0.982
  Sub::Exporter::Progressive: 0.001006
  Term::ReadKey: 2.3
  Text::Autoformat: 1.669002
  Time::Zone: 2.24
  Try::Tiny: 0.09
  Unexpected: v0.1.0
  YAML::Syck: 1.17
  namespace::autoclean: 0.13
  namespace::clean: 0.23
  perl: 5.01
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Class-Usul
  homepage: http://www.roxsoft.co.uk
  license: http://dev.perl.org/licenses/
version: v0.21.1
